### ISSUE TITLE
error

### ISSUE THREAD

**Issue by elfata92** [aldysetiaa/voice_indonesian#2]
GET http://localhost/voice_indonesian-main/style.css net::ERR_ABORTED 404 (Not Found)
vcs.php:20          GET http://localhost/voice_indonesian-main/1.mp3 404 (Not Found)
script.js:1          GET http://localhost/voice_indonesian-main/setting.txt

**Comment by aldysetiaa** [comment]
Sudah di update ya,
https://github.com/aldysetiaa/voice_indonesian/commit/89ee771d98aedf7d04ae675cea650721dc73e8ad
